# Placeholder for eta-ml-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eta-model-pvc
  namespace: duk-bus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
